# Generated by Django 5.0.6 on 2026-09-19 09:10

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
