# Generated by Django 5.0.6 on 2026-07-28 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('title', models.CharField(help_text='Certificate or course title.', max_length=200)),
                ('issuing_organization', models.CharField(help_text="Organization that issued the certificate, e.g. 'AWS', 'Coursera'.", max_length=200)),
                ('issue_date', models.DateField(help_text='Date the certificate was issued.')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date, if applicable.', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Unique credential ID provided by the issuer.', max_length=200)),
                ('credential_url', models.URLField(blank=True, help_text='URL to verify the credential online.')),
                ('image', models.ImageField(blank=True, help_text='Certificate image or badge.', null=True, upload_to='certificates/')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured certificates appear on the homepage.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(help_text="e.g. 'BSc in Computer Science'.", max_length=200)),
                ('field_of_study', models.CharField(blank=True, help_text="e.g. 'Software Engineering'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently enrolled.', null=True)),
                ('grade', models.CharField(blank=True, help_text='GPA, grade, or classification.', max_length=50)),
                ('institution_url', models.URLField(blank=True)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='institutions/')),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('title', models.CharField(help_text='Project title.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='One-line summary shown on project cards.', max_length=300)),
                ('description', models.TextField(help_text='Full project description. Supports markdown.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Main image shown on the project card.', null=True, upload_to='projects/thumbnails/')),
                ('github_url', models.URLField(blank=True, help_text='Link to the GitHub repository.')),
                ('live_url', models.URLField(blank=True, help_text='Link to the live demo.')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured projects appear at the top of the portfolio.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order. Lower numbers appear first.')),
                ('started_at', models.DateField(blank=True, help_text='When work on this project began.', null=True)),
                ('completed_at', models.DateField(blank=True, help_text='When the project was completed.', null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('name', models.CharField(help_text="Skill name, e.g. 'Docker', 'Python', 'AWS EC2'.", max_length=100)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('proficiency_percent', models.PositiveSmallIntegerField(default=50, help_text='Proficiency as a percentage (0–100) for progress bars.')),
                ('icon', models.CharField(blank=True, help_text="Icon class or Devicons class, e.g. 'devicon-python-plain'.", max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured skills are highlighted on the homepage.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the category.')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('name', models.CharField(help_text="Category name, e.g. 'Cloud & DevOps'.", max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name. Auto-generated.', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon class name, e.g. 'fa-solid fa-cloud'.", max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order. Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, help_text="e.g. 'Remote' or 'Colombo, Sri Lanka'.", max_length=200)),
                ('description', models.TextField(help_text='Responsibilities and achievements. Supports markdown.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current position.', null=True)),
                ('company_url', models.URLField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('is_current', models.BooleanField(default=False, help_text="Marks this as the current position. Sets end_date display to 'Present'.")),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('image', models.ImageField(help_text='Screenshot or demo image.', upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption displayed below the image.', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='The primary image is used as the project thumbnail fallback.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(help_text='The project this screenshot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='portfolio.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='portfolio.skill')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this project.', related_name='projects', through='portfolio.ProjectSkill', to='portfolio.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(help_text='The category this skill belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('category', 'name')},
        ),
    ]
