# Generated by Django 5.0.6 on 2026-09-19 09:10

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Certificate image or badge.', null=True, upload_to='certificates/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutions/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Main image shown on the project card.', null=True, upload_to='projects/thumbnails/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Screenshot or demo image.', upload_to='projects/screenshots/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
