# Generated by Django 5.0.6 on 2026-07-27 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('title', models.CharField(blank=True, help_text="Professional title, e.g. 'Full Stack Developer & DevOps Engineer'.", max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short biography displayed on the About section.')),
                ('location', models.CharField(blank=True, help_text="e.g. 'Colombo, Sri Lanka'.", max_length=100)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, help_text='Years of professional experience.', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile photo displayed on the homepage.', null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='Latest resume PDF. Visitors will always download this version.', null=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True, help_text='Full GitHub profile URL.')),
                ('linkedin_url', models.URLField(blank=True, help_text='Full LinkedIn profile URL.')),
                ('email', models.EmailField(blank=True, help_text='Public contact email displayed on the website.', max_length=254)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL if different from this portfolio.')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description for the homepage (max 160 chars).', max_length=160)),
                ('user', models.OneToOneField(help_text='The Django user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
