# Generated by Django 5.0.6 on 2026-09-19 09:10

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile photo displayed on the homepage.', null=True, upload_to='profile/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Latest resume PDF.', null=True, upload_to='resume/', validators=[apps.core.validators.validate_pdf_file]),
        ),
    ]
